development:
  adapter: postgresql
  encoding: unicode
  database: project_time
  host: 127.0.0.1
  port: 5433
  pool: 5
  timeout: 5000
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: project_time
  host: 127.0.0.1
  port: 5432
  pool: 5
  timeout: 5000
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: project_time
  host: 127.0.0.1
  port: 5433
  pool: 5
  timeout: 5000
  username: postgres
